name: CI Maven build
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v2
        with:
          # Disabling shallow clone for SonarCloud analysis
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Compile
        run: mvn compile

      - name: Execute tests
        run: mvn test

      - name: Send coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: target/site/jacoco/jacoco.xml
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: SonarCloud Scan
        run: mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=boxedroid -Dsonar.organization=bmarsaud -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}